name: Build Debian Package

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest 
    container: debian:bookworm-slim  # Actual build environment (Debian 12)
    
    steps:
    - name: Install git and basic tools
      run: |
        apt-get update
        apt-get install -y git curl 
        
        # Show Debian version
        cat /etc/debian_version
        echo "Building on Debian $(cat /etc/debian_version)"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install PHP and build dependencies
      run: |
        apt-get update
        apt-get install -y php8.2-cli php8.2-mysql php8.2-curl php8.2-mbstring php8.2-xml unzip dpkg-dev
        
        # Install Composer
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

    - name: Validate composer.json
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: debian-bookworm-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          debian-bookworm-php-

    - name: Install PHP dependencies
      run: composer install --no-dev --optimize-autoloader --no-interaction

    - name: Run tests
      run: |
        # Test configuration parsing
        php -r "
        \$config = parse_ini_file('config.ini', true);
        if (\$config === false) {
          echo 'Failed to parse config.ini\n';
          exit(1);
        }
        echo 'Configuration validation passed\n';
        "
        
        # Test PHP syntax
        php -l postal_monitor.php
        
        # Test class loading (basic)
        php -r "
        require_once 'vendor/autoload.php';
        if (!class_exists('PHPMailer\PHPMailer\PHPMailer')) {
          echo 'PHPMailer not found\n';
          exit(1);
        }
        echo 'Dependencies loaded correctly\n';
        "

    - name: Set package version
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        else
          VERSION="1.0.0-${GITHUB_SHA::8}"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION"

    - name: Update package version in build script
      run: |
        sed -i 's/VERSION="1.0.0"/VERSION="${{ steps.version.outputs.version }}"/' build_deb.sh

    - name: Make build script executable
      run: chmod +x build_deb.sh

    - name: Build Debian package
      run: ./build_deb.sh

    - name: List built packages
      run: ls -la *.deb

    - name: Test package installation
      run: |
        # Test package structure
        dpkg-deb --contents postal-monitor_*.deb
        
        # Test package info
        dpkg-deb --info postal-monitor_*.deb

    - name: Upload package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: debian-package-${{ steps.version.outputs.version }}
        path: postal-monitor_*.deb
        retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    container: debian:bookworm-slim
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Install git
      run: |
        apt-get update
        apt-get install -y git

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set version
      id: version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Download package artifact
      uses: actions/download-artifact@v4
      with:
        name: debian-package-${{ steps.version.outputs.version }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.version.outputs.version }}
        body: |
          ## Postal Monitor v${{ steps.version.outputs.version }}
          
          ### Installation
          
          Download the `.deb` package and install:
          ```bash
          sudo dpkg -i postal-monitor_${{ steps.version.outputs.version }}_all.deb
          sudo apt-get install -f  # if there are dependency issues
          ```
          
          ### Configuration
          
          1. Edit the configuration file:
             ```bash
             sudo vi /etc/postal-monitor/config.ini
             ```
          
          2. Start the service:
             ```bash
             sudo systemctl start postal-monitor
             sudo systemctl enable postal-monitor
             ```
          
          3. Check status and logs:
             ```bash
             sudo systemctl status postal-monitor
             sudo journalctl -u postal-monitor -f
             ```
          
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./postal-monitor_${{ steps.version.outputs.version }}_all.deb
        asset_name: postal-monitor_${{ steps.version.outputs.version }}_all.deb
        asset_content_type: application/vnd.debian.binary-package
